language: cpp

install:
  - sudo apt-get install -qq libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
    

before_script:
  - sudo apt-get install 

script:
  - cmake .
  - cmake --build .
  - ctest -V
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T otus_cpp_lesson_01_01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uchernikoff:$BINTRAY_API_KEY https://api.bintray.com/content/chernikoff/otus/lesson_01_01/$TRAVIS_BUILD_NUMBER/otus_cpp_lesson_01_01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1;
